// Isolated Mock browser QA; routes API traffic to the dedicated local QA server.
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {mkdir, writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium} = await import(pathToFileURL(resolve(process.argv[2])).href);
const out = resolve(process.argv[3] || 'evidence/studio-v030/browser-mock');
await mkdir(out, {recursive:true});
const browser = await chromium.launch({channel:'msedge', headless:true});
const errors = [], checks = {};
try {
  const page = await browser.newPage({viewport:{width:1440,height:1050}, acceptDownloads:true});
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/**', async route => {
    const u = new URL(route.request().url());
    const response = await route.fetch({url:'http://127.0.0.1:8123'+u.pathname+u.search});
    await route.fulfill({response});
  });
  await page.goto('http://127.0.0.1:5173/');
  await page.getByRole('button',{name:'AI为何会答错 ↗'}).click();
  await page.getByRole('button',{name:'生成作品并自动审核 →'}).click();
  await page.getByRole('button',{name:'放大海报'}).waitFor();
  await page.waitForFunction(() => document.querySelector('[role=status]')?.textContent.includes('Mock演示完成'));
  const id = await page.getByLabel('打开已保存项目').inputValue();
  assert(id);
  checks.mock_project_saved_and_polled = true;
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({path:out+'/desktop.png',fullPage:true});
  const geometry = await page.locator('.studio-scroll').evaluate(el => ({client:el.clientHeight,scroll:el.scrollHeight,overflow:getComputedStyle(el).overflowY}));
  assert.equal(geometry.overflow,'auto');assert(geometry.scroll>geometry.client);
  checks.independent_results_scroll = true;
  await page.getByRole('button',{name:'放大海报'}).click();
  await page.getByRole('dialog',{name:'海报大图'}).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  checks.lightbox_escape = true;
  await page.getByRole('tab',{name:'独立分镜'}).click();
  await page.getByRole('button',{name:'预演分镜',exact:true}).click();
  assert.equal(await page.locator('.studio-animatic.playing').count(),1);
  await page.getByRole('button',{name:'暂停',exact:true}).click();
  checks.animatic_controls = true;
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'导出草稿包 ↓'}).click();
  const download=await downloadPromise;
  assert(download.suggestedFilename().endsWith('.zip'));
  await download.saveAs(out+'/mock-export.zip');
  checks.export_zip = true;
  await page.reload();
  await page.getByLabel('打开已保存项目').selectOption(id);
  await page.getByRole('button',{name:'放大海报'}).waitFor();
  checks.reload_restores_project = true;
  await page.getByRole('tab',{name:'证据与版本'}).click();
  await page.locator('.studio-evidence').first().waitFor();
  await page.screenshot({path:out+'/evidence.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:out+'/mobile.png',fullPage:true});
  const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:innerWidth}));
  assert(width.scroll<=width.client, JSON.stringify(width));
  checks.mobile_no_horizontal_overflow = true;
  assert.deepEqual(errors,[]);
  await writeFile(out+'/report.json',JSON.stringify({checks,errors},null,2));
  console.log(JSON.stringify({checks,errors}));
} finally {await browser.close();}
